"""Step 3 & 4: LLM 기반 한국어 번역 + GuruNote 스타일 마크다운 요약.

- Provider: OpenAI (gpt-5.4) 또는 Anthropic (claude-sonnet-4-6)
- 긴 영상 대응: 세그먼트를 토큰 한도에 맞춰 청크 분할 → 청크별 번역 → 병합
- 번역 결과를 다시 요약 단계에 통째로 넣어 최종 마크다운을 만든다.

`gurunote/llm.py` 한 파일이던 것을 패키지로 나눴다. 3447행에 함수 61개가 모여 있어
무엇이 무엇에 딸린 것인지 읽어내기 어려웠다. 하위 모듈은 의존 방향이 한쪽으로만
흐른다: client → (prompts, chunking, context) → entities → postprocess → translate/summarize.

기존 `from gurunote.llm import X` 를 그대로 쓸 수 있게 여기서 전부 re-export 한다.
테스트와 호출부가 private 이름까지 참조하고 있어 공개 이름만 내보내면 깨진다.
"""
from __future__ import annotations

from gurunote.llm.client import (  # noqa: F401
    ProgressFn,
    LLMConfig,
    _int_env,
    _float_env,
    _log,
    _MAX_RETRIES,
    _INITIAL_BACKOFF,
    _call_llm,
    _call_llm_once,
    TRANSLATION_MAX_TOKENS,
    SUMMARY_MAX_TOKENS,
    _XGRAMMAR_CHECK_CACHE,
    _XGRAMMAR_CHECK_TTL_SEC,
    _get_omlx_signature,
    _check_xgrammar_available,
    test_connection,
    DEFAULT_LLM_CHUNK_TIMEOUT_SEC,
    LLM_HTTP_TIMEOUT_SEC,
    _call_with_wall_clock_timeout,
    _call_llm_once_with_reason,
    _call_llm_with_continuation,
)
from gurunote.llm.prompts import (  # noqa: F401
    _SHARED_LANG_RULES,
    TRANSLATION_SYSTEM_PROMPT,
    SUMMARY_SYSTEM_PROMPT,
    METADATA_SYSTEM_PROMPT,
)
from gurunote.llm.chunking import (  # noqa: F401
    CHUNK_DELAY_SEC,
    DEFAULT_CHUNK_CHAR_LIMIT,
    MAX_SEGMENTS_PER_CHUNK,
    RESPLIT_CHAR_LIMIT,
    RESPLIT_SEGMENT_LIMIT,
    chunk_segments,
    _segments_to_user_block,
)
from gurunote.llm.context import (  # noqa: F401
    _MAX_CONTEXT_DESCRIPTION,
    _MAX_CONTEXT_SUBTITLE,
    build_video_context_block,
)
from gurunote.llm.entities import (  # noqa: F401
    _detect_unexpected_changes,
    _canonicalize_entity_names,
    _SPEAKER_LINE_RE,
    _ENGLISH_NAME_RE,
    _extract_entities,
    _build_entity_cache_block,
    _bootstrap_entity_cache_from_metadata,
    CACHE_DIR,
    LOANWORD_SPEC_VERSION,
    CACHE_SCHEMA_VERSION,
    _LOANWORD_FILE,
    _CANONICALIZE_MAX_BODY_CHARS,
    _compute_cache_key_from_title,
    _load_loanword_short_version,
    _load_loanword_full_body,
    _LOANWORD_SHORT,
    _get_cache_file_path,
    _save_entity_cache,
    _load_entity_cache,
    _load_entity_cache_full,
    load_speaker_names,
    _verify_entities_with_search,
    load_stt_corrections,
    _CANONICAL_NAMES_PATH,
    _CANONICAL_NAMES_DEFAULT,
    _load_canonical_names,
    _save_canonical_names,
    _canonical_effective,
    _record_auto_spellings,
    _persist_auto_spellings,
    _apply_canonical_to_entity_cache,
    _apply_canonical_to_speaker_cache,
    refresh_canonical_in_markdown,
)
from gurunote.llm.postprocess import (  # noqa: F401
    _REPEATED_ANNOTATION_RE,
    _strip_repeated_annotations,
    _CJK_LOOKUP_PATH,
    _CJK_LOOKUP_CACHE,
    _CJK_DETECT_RE,
    _BRACKETED_CJK_RE,
    _SEGMENT_PREFIX_RE,
    _load_cjk_lookup,
    _detect_cjk_outside_brackets,
    _apply_cjk_dict_lookup,
    _llm_remap_cjk,
    post_process_cjk,
    post_process_cjk_text,
    _ENGLISH_ANNOT_RE,
    _correct_english_annotations,
    _KOREAN_ANNOT_RE,
    _correct_korean_in_annotations,
    _SPEAKER_PREFIX_RE,
    _strip_input_speaker_prefix,
    _DEDUP_LINE_RE,
    _DEDUP_MIN_LEN,
    _DEDUP_MIN_RUN,
    _DEDUP_SKIP_PREFIXES,
    _collapse_repeated_lines,
)
from gurunote.llm.translate import (  # noqa: F401
    translate_transcript,
    TIMEOUT_PADDING_MARKER,
    _build_freeform_translation_prompt,
    _build_alignment_prompt,
    _build_index_mapping_prompt,
    _call_llm_with_index_mapping,
    _post_process_two_pass_outputs,
    _resolve_speaker_label,
    _translate_chunk_two_pass,
    _recover_empty_outputs,
    translate_chunk_index_mapping_v2,
)
from gurunote.llm.summarize import (  # noqa: F401
    summarize_translation,
    extract_metadata,
    _excerpt_for_metadata,
    _parse_metadata_json,
)

__all__ = [
    'ProgressFn',
    '_SHARED_LANG_RULES',
    'TRANSLATION_SYSTEM_PROMPT',
    'SUMMARY_SYSTEM_PROMPT',
    'LLMConfig',
    '_int_env',
    '_float_env',
    '_log',
    '_MAX_RETRIES',
    '_INITIAL_BACKOFF',
    'CHUNK_DELAY_SEC',
    '_call_llm',
    '_call_llm_once',
    'DEFAULT_CHUNK_CHAR_LIMIT',
    'MAX_SEGMENTS_PER_CHUNK',
    'RESPLIT_CHAR_LIMIT',
    'RESPLIT_SEGMENT_LIMIT',
    'TRANSLATION_MAX_TOKENS',
    'SUMMARY_MAX_TOKENS',
    'chunk_segments',
    '_segments_to_user_block',
    '_MAX_CONTEXT_DESCRIPTION',
    '_MAX_CONTEXT_SUBTITLE',
    'build_video_context_block',
    '_REPEATED_ANNOTATION_RE',
    '_strip_repeated_annotations',
    '_CJK_LOOKUP_PATH',
    '_CJK_LOOKUP_CACHE',
    '_CJK_DETECT_RE',
    '_BRACKETED_CJK_RE',
    '_SEGMENT_PREFIX_RE',
    '_load_cjk_lookup',
    '_detect_cjk_outside_brackets',
    '_apply_cjk_dict_lookup',
    '_llm_remap_cjk',
    'post_process_cjk',
    'post_process_cjk_text',
    '_detect_unexpected_changes',
    '_canonicalize_entity_names',
    '_SPEAKER_LINE_RE',
    '_ENGLISH_NAME_RE',
    '_ENGLISH_ANNOT_RE',
    '_correct_english_annotations',
    '_KOREAN_ANNOT_RE',
    '_correct_korean_in_annotations',
    '_extract_entities',
    '_build_entity_cache_block',
    '_bootstrap_entity_cache_from_metadata',
    'CACHE_DIR',
    'LOANWORD_SPEC_VERSION',
    'CACHE_SCHEMA_VERSION',
    '_LOANWORD_FILE',
    '_CANONICALIZE_MAX_BODY_CHARS',
    '_compute_cache_key_from_title',
    '_load_loanword_short_version',
    '_load_loanword_full_body',
    '_LOANWORD_SHORT',
    '_get_cache_file_path',
    '_save_entity_cache',
    '_load_entity_cache',
    '_load_entity_cache_full',
    'load_speaker_names',
    '_verify_entities_with_search',
    'load_stt_corrections',
    '_XGRAMMAR_CHECK_CACHE',
    '_XGRAMMAR_CHECK_TTL_SEC',
    '_get_omlx_signature',
    '_check_xgrammar_available',
    '_CANONICAL_NAMES_PATH',
    '_CANONICAL_NAMES_DEFAULT',
    '_load_canonical_names',
    '_save_canonical_names',
    '_canonical_effective',
    '_record_auto_spellings',
    '_persist_auto_spellings',
    '_apply_canonical_to_entity_cache',
    '_apply_canonical_to_speaker_cache',
    'refresh_canonical_in_markdown',
    'translate_transcript',
    'summarize_translation',
    'METADATA_SYSTEM_PROMPT',
    'extract_metadata',
    '_excerpt_for_metadata',
    '_parse_metadata_json',
    'test_connection',
    'DEFAULT_LLM_CHUNK_TIMEOUT_SEC',
    'TIMEOUT_PADDING_MARKER',
    'LLM_HTTP_TIMEOUT_SEC',
    '_call_with_wall_clock_timeout',
    '_call_llm_once_with_reason',
    '_build_freeform_translation_prompt',
    '_build_alignment_prompt',
    '_build_index_mapping_prompt',
    '_call_llm_with_continuation',
    '_call_llm_with_index_mapping',
    '_SPEAKER_PREFIX_RE',
    '_strip_input_speaker_prefix',
    '_DEDUP_LINE_RE',
    '_DEDUP_MIN_LEN',
    '_DEDUP_MIN_RUN',
    '_DEDUP_SKIP_PREFIXES',
    '_collapse_repeated_lines',
    '_post_process_two_pass_outputs',
    '_resolve_speaker_label',
    '_translate_chunk_two_pass',
    '_recover_empty_outputs',
    'translate_chunk_index_mapping_v2',
]
